<?php
// $Id$

/**
 * @file
 * Base module for all CRM interactions.
 * @author Michael Prasuhn <mike@shomeya.com>
 * @link http://shomeya.com
 * @package crm
 */

/**
 * Implementation of hook_perm().
 */
function crm_perm() {
  return array('access crm');
}

/**
 * Implementation of hook_menu().
 */
function crm_menu() {
  $items = array();
  $items['admin/crm'] = array(
    'title' => 'CRM Administration',
    'description' => 'Access and administer CRM features.',
    'position' => 'left',
    'weight' => -5,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access crm'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  return $items;
}
